---
# get aws eks kubernetes configuration. ------------------------------------------------------------
- name: get aws eks kubeconfig playbook
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes

  vars:
    env_vars:
      eks_kubeconfig_filepath: "{{ lookup('env', 'eks_kubeconfig_filepath') | default(ansible_env.HOME + '/.kube/config', true) }}"

  tasks:
    # run the deploy teastore application script.
    - name: get eks kubeconfig
      shell:
        chdir: "{{ ansible_env.HOME }}"
        cmd: "aws eks --region ${aws_region_name} update-kubeconfig --name ${aws_eks_cluster_name}"
        creates: "{{ ansible_env.HOME }}/.kube/config"
      environment: "{{ env_vars }}"
      register: get_eks_kubeconfig

    # print the results from the deploy script.
    - name: print deploy teastore microservice application results
      debug:
        var: get_eks_kubeconfig.stdout_lines
